// <auto-generated />
using System;
using AfterFrame.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AfterFrame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AfterFrameDbContext))]
    [Migration("20261002072943_AddExternalCatalogMetadata")]
    partial class AddExternalCatalogMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AfterFrame.Domain.Library.LibraryEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("LastWatchedEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("last_watched_episode");

                    b.Property<int?>("LastWatchedSeason")
                        .HasColumnType("integer")
                        .HasColumnName("last_watched_season");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId", "TitleId");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_library_entries_title_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_library_entries_user_id_status");

                    b.ToTable("library_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_library_entries_progress", "(\n    \"last_watched_season\" IS NULL\n    AND \"last_watched_episode\" IS NULL\n)\nOR\n(\n    \"last_watched_season\" IS NOT NULL\n    AND \"last_watched_season\" > 0\n    AND \"last_watched_episode\" IS NOT NULL\n    AND \"last_watched_episode\" > 0\n)");

                            t.HasCheckConstraint("ck_library_entries_rating", "\"rating\" IS NULL\nOR\n(\n    \"rating\" >= 0.5\n    AND \"rating\" <= 10\n    AND MOD(\"rating\" * 2, 1) = 0\n)");
                        });
                });

            modelBuilder.Entity("AfterFrame.Domain.Titles.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("AfterFrame.Domain.Titles.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<decimal?>("ExternalRating")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("external_rating");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_source");

                    b.Property<int>("ExternalVoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("external_vote_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_path");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("publication_status");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<int>("Tags")
                        .HasColumnType("integer")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_titles_created_by_user_id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_titles_external_identity")
                        .HasFilter("\"external_source\" IS NOT NULL AND \"external_id\" IS NOT NULL");

                    b.ToTable("titles", null, t =>
                        {
                            t.HasCheckConstraint("ck_titles_external_rating", "(\n    \"origin\" = 'External'\n    AND\n    (\n        (\n            \"external_rating\" IS NULL\n            AND \"external_vote_count\" = 0\n        )\n        OR\n        (\n            \"external_rating\" IS NOT NULL\n            AND \"external_rating\" >= 0\n            AND \"external_rating\" <= 10\n            AND \"external_vote_count\" > 0\n        )\n    )\n)\nOR\n(\n    \"origin\" = 'UserCreated'\n    AND \"external_rating\" IS NULL\n    AND \"external_vote_count\" = 0\n)");

                            t.HasCheckConstraint("ck_titles_origin", "(\n    \"origin\" = 'External'\n    AND \"publication_status\" = 'Published'\n    AND \"external_source\" IS NOT NULL\n    AND \"external_id\" IS NOT NULL\n    AND \"created_by_user_id\" IS NULL\n)\nOR\n(\n    \"origin\" = 'UserCreated'\n    AND \"external_source\" IS NULL\n    AND \"external_id\" IS NULL\n    AND \"created_by_user_id\" IS NOT NULL\n)");

                            t.HasCheckConstraint("ck_titles_release_year", "\"release_year\" > 0");
                        });
                });

            modelBuilder.Entity("AfterFrame.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199f3f4-7c00-7000-8000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Demo User"
                        });
                });

            modelBuilder.Entity("TitleGenre", b =>
                {
                    b.Property<Guid>("title_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("genre_id")
                        .HasColumnType("uuid");

                    b.HasKey("title_id", "genre_id");

                    b.HasIndex("genre_id")
                        .HasDatabaseName("ix_title_genres_genre_id");

                    b.ToTable("title_genres", (string)null);
                });

            modelBuilder.Entity("AfterFrame.Domain.Library.LibraryEntry", b =>
                {
                    b.HasOne("AfterFrame.Domain.Titles.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterFrame.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AfterFrame.Domain.Titles.Title", b =>
                {
                    b.HasOne("AfterFrame.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TitleGenre", b =>
                {
                    b.HasOne("AfterFrame.Domain.Titles.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AfterFrame.Domain.Titles.Title", null)
                        .WithMany()
                        .HasForeignKey("title_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
